image: debian/buster
environment:
  PROJECT_NAME: robinopletal.com
  CI_REGISTRY: docker.io
  CI_REGISTRY_USER: fourstepper
  CI_REGISTRY_IMAGE: $CI_REGISTRY/$CI_REGISTRY_USER/$PROJECT_NAME
secrets:
  - 9c21e186-72c5-4633-b9da-5ca7faa0342a
packages:
  - sudo
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
tasks:
  - docker-setup: |
      curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
      sudo add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable"
      sudo apt-get update
      sudo apt-get install docker-ce docker-ce-cli containerd.io
      sudo systemctl start docker
  - docker-build: |
      cd "$PROJECT_NAME"
      sudo docker build -t "$CI_REGISTRY_IMAGE" .
  - verify: |
      sudo docker run -d --name "test" -e USER='admin' -e PASSWORD='password' \
      -e LISTEN_METHOD='irc+insecure' -e LISTEN_HOST='0.0.0.0' \
      -e LISTEN_PORT='6667' -p 6667:6667 "$CI_REGISTRY_IMAGE"
      cd "$PROJECT_NAME"
      sudo ./ci-check.sh test 10
  - docker-push: |
      sudo docker login -u "$CI_REGISTRY_USER" --password-stdin=true < ~/.secrets/ci_registry_password
      sudo docker push "$CI_REGISTRY_IMAGE"

