when:
  event:
    # don't run on pull requests
    - push
    - manual
  path:
    include: [ 'Dockerfile', '.woodpecker/**', 'site/**', '.gitmodules', 'nginx/**' ]

steps:
  publish-image-branch:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/robinopletal.com
      registry: codeberg.org
      dockerfile: Dockerfile
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
    when:
      - evaluate: CI_COMMIT_BRANCH != CI_REPO_DEFAULT_BRANCH

  publish-image-latest:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/${CI_REPO_OWNER}/robinopletal.com
      registry: codeberg.org
      tags: latest, ${CI_COMMIT_SHA}
      dockerfile: Dockerfile
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
    when:
      - evaluate: CI_COMMIT_BRANCH == CI_REPO_DEFAULT_BRANCH
