---
name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "10 1 * * 0"

jobs:
  # Test the image builds and works correctly.
  CI:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t ${{ github.repository }} .

      - name: Run the built image.
        run: docker run --name test-container -d ${{ github.repository }}

      - name: Verify that the image is running
        run: docker exec --tty test-container env TERM=xterm cat /etc/os-release

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:latest
